# Generated by Django 5.2 on 2025-04-05 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.region')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.district')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('subject_taught', models.CharField(max_length=100)),
                ('teaching_experience', models.PositiveIntegerField(help_text='Years of teaching experience')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_district', to='transfers.district')),
                ('current_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_region', to='transfers.region')),
                ('current_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_school', to='transfers.school')),
                ('desired_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_district', to='transfers.district')),
                ('desired_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_region', to='transfers.region')),
                ('desired_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_school', to='transfers.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ward', to='transfers.ward')),
                ('desired_ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_ward', to='transfers.ward')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.ward'),
        ),
    ]
