# Generated by Django 5.2 on 2025-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transferrequest_district_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='form_four_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='form_four_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='form_six_or_diploma_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='form_six_or_diploma_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='university_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='university_reg_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
