# Generated by Django 5.2 on 2025-04-14 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transferrequest_form_four_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
