# Generated by Django 5.2 on 2025-04-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_cancellationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrecord',
            name='transfer_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transfers.transferrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='cancel_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='current_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_current_district', to='transfers.district'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='current_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_current_region', to='transfers.region'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='current_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_current_school', to='transfers.school'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='current_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_current_ward', to='transfers.ward'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='desired_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_desired_district', to='transfers.district'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='desired_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_desired_region', to='transfers.region'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='desired_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_desired_school', to='transfers.school'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='desired_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_desired_ward', to='transfers.ward'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
