# Generated by Django 5.2 on 2025-04-24 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0009_alter_cancellationrecord_transfer_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerequest',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='sender',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='school_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_1', to='transfers.school'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='school_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_2', to='transfers.school'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='teacher_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='teacher_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CancellationRecord',
        ),
    ]
