# Generated by Django 5.2 on 2025-04-24 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0010_rename_sent_at_exchangerequest_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='school_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_1', to='transfers.school'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='school_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_2', to='transfers.school'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='teacher_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='teacher_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
