# Generated by Django 5.2 on 2025-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0015_teacherprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='district_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='school_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tamisemi_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
