# Generated by Django 5.2 on 2025-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0018_message_is_draft_message_is_spam_messagethread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
